### ISSUE TITLE
lca index "WARNING: no lineage assignment"

### ISSUE THREAD

**Issue by ReneKat** [dib-lab/sourmash#1008]
Hello sourmash community!

I am trying to create my own lca database from 44 Metagenomic bins. 
My sponge_GTDB.csv is formatted as such:

```
MAGs,Domain,Phylum,Class,Order,Family,Genus,Species
cluster_merged_7,Bacteria,Proteobacteria,Gammaproteobacteria,Immundisolibacterales,na,na,I. cernigliae (GCF_001697225.1)
cluster_merged_6,Bacteria,Chloroflexota,Dehalococcoidia,UBA1151,na,na,na
cluster_merged_5,Bacteria,Bdellovibrionota,Bdellovibrionia,Bdellovibrionales,UBA1609,na,na
cluster_merged_4,Bacteria,Bdellovibrionota,Bdellovibrionia,Bdellovibrionales,UBA1609,na,na
cluster_merged_3,Bacteria,Chloroflexota,Dehalococcoidia,UBA1151,bin127,bin127,SAR202 cluster (GCA_002239045.1)
cluster_merged_2,Bacteria,Latescibacterota,UBA2968,UBA8231,GCA-002724215,GCA-2724215,Gemmatimonadetes bacterium (GCA_002724215.1)
cluster_merged_1,Bacteria,Bdellovibrionota,Bacteriovoracia,Bacteriovoracales,Bacteriovoracaceae,na,na
cluster_DBSCAN_round9_49,Bacteria,Acidobacteriota,bin61,bin61,bin61,bin61,Acidobacteria bacterium (GCA_002238705.1)
cluster_DBSCAN_round9_3,Bacteria,Proteobacteria,Alphaproteobacteria,UBA828,UBA828,na,na
```

I computed signatures for each bin:

```
sourmash compute -k 31 --scaled=1000 *fasta\
--merge sponge\
-o sponge_meta_bin_k31.sigs
```

Then run lca index:

`sourmash lca index -f sponge_database.csv sponge.lca.json sponge_meta_bin_k31.sigs --report REPORT
`
I receive the following output:

> == This is sourmash version 3.3.0. ==
> == Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
> 
> examining spreadsheet headers...
> ** assuming column '﻿MAGs' is identifiers in spreadsheet
> ** assuming column 'Domain' is superkingdom in spreadsheet
> 44 distinct identities in spreadsheet out of 44 rows.
> 37 distinct lineages in spreadsheet out of 44 rows.
> 0 assigned lineages out of 37 distinct lineages in spreadsheet.
> 1 identifiers used out of 44 distinct identifiers in spreadsheet.
> saving to LCA DB: sponge.lca.json
> WARNING: no lineage provided for 1 signatures.
> WARNING: no signatures for 44 lineage assignments.
> WARNING: 37 unused lineages.
> WARNING: 44 unused identifiers.
> generating a report and saving in 'REPORT'

Would someone be able to offer me direction: Why are the signatures not matching up to the lineages? 

Thank you for your support!
René

**Comment by ctb** [comment]
hi @ReneKat thank you for checking in!

I can't be quite sure, but it looks like your signature names may not match up.  Specifically, if you look at the lineage spreadsheet, you have names like `cluster_merged_7`. But it looks like you are calculating only a single signature total, using the `--merge` option to sourmash compute, and giving that signature the name `sponge`.

If you run `sourmash sig describe sponge_meta_bin_k31.sigs` you should see that you have only one signature in there, and its name is `sponge`.

What you need to do instead is calculate a different signature for each bin, e.g. something like

`sourmash compute --merge cluster_merged_7 cluster_merged_7.fasta`

and then give *.fasta.sig to sourmash lca index.

This is a bit annoying because you need to write a different compute command for each bin. The _easiest_ way I've found to deal with this is to have the first FASTA sequence in each bin have the name of the cluster, e.g. the file begins with >cluster_merged_7.

I hope that helps - please let us know as you run into trouble and we'll try to respond quickly!

**Comment by ReneKat** [comment]
Hi @ctb,
I really appreciate your quick reply.
You were exactly right! I ran this script to compute signatures for each bin:

`for prefix in `more bin_prefix.txt | sort -u`; do
  echo ${prefix}
  sourmash compute -k 31 --scaled=1000 ${prefix}.fasta --merge ${prefix} -o sponge_meta_bin_sigs/${prefix}.sig
done
`

Then created the lca_database

`sourmash lca index -f sponge_database.csv sponge.lca.json sponge_meta_bin_sigs/*sig --report REPORT
`

Now the only lineage without assignment is the unclustered (expected).

> WARNING: no lineage assignment for cluster_unclustered.
> 37 assigned lineages out of 37 distinct lineages in spreadsheet.
> 45 identifiers used out of 44 distinct identifiers in spreadsheet.
> saving to LCA DB: sponge.lca.json
> WARNING: no lineage provided for 1 signatures.
> generating a report and saving in 'REPORT'

Thank you very much!

**Comment by ctb** [comment]
Excellent, and thank you for circling back and letting us know!
