### ISSUE TITLE
remove support for Python 2.x, require python 3.7 or later

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1033]
This is the issue that @luizirber has been waiting for for years!!

TODO  --

Make necessary documentation (install docs, requirements docs) changes.
Adjust conda recipe
Remove python 2.7 builder on CI.
Remove all of the __future__ statements.
change/fix Enum import stuff

remove compat code, including
```
sourmash/_compat.py:PY2 = sys.version_info[0] == 2
sourmash/lca/command_index.py:    if sys.version_info < (3, ):
sourmash/signature.py:                if sys.version_info >= (3,):
```

**Comment by ctb** [comment]
also https://github.com/dib-lab/sourmash/issues/1043

**Comment by luizirber** [comment]
I think we should move the minimum supported Python 3 according to the NumPy policy:
https://numpy.org/neps/nep-0029-deprecation_policy.html
Although... this would mean dropping 3.6 yesterday =P

OK, maybe making it 3.6+? I don't see why support 3.4, maaaybe support 3.5, but bioconda only builds for 3.6 and 3.7 (and slowly transitioning into 3.8).

**Comment by ctb** [comment]
I'm good with following that NEP.  Any downsides?

(The availability of conda install really makes this a no-brainer for me.)

**Comment by luizirber** [comment]
> I'm good with following that NEP. Any downsides?

It's a faster deprecation cadence than what we had previously, but other than that I really like the reasoning in the NEP.

One point is that we don't really support anything besides the latest released sourmash version, which is different than what NumPy does.

> (The availability of conda install really makes this a no-brainer for me.)

We might also consider what are the default Python versions on MacOS and Linux (Ubuntu LTS?), because that might make it harder to install in non-conda places. Although at this point that's "advanced usage", and it's up to the user to install the correct Python?

**Comment by ctb** [comment]
Yes, I think it is ok to have a reduced/minimal support policy. At this point I'm still not sure how many people are using sourmash, and in the absence of that and more dedicated funding I don't want to complicate our lives for this unknown! I also don't think software support is a differentiator for adoption here, to be blunt...

Also, I would be totally fine with releasing maintenance versions of 3.x if we discover major bugs...
