### ISSUE TITLE
containment vs. resemblance

### ISSUE THREAD

**Issue by viehwegerlib** [dib-lab/sourmash#125]
Dear all,

I am probably missing some minhash theory detail here, concerning the calculation of the Jaccard index in sourmash: 

I understand that the Jaccard index is what is referred to as "resemblance" in Broder's original paper. Besides that, there is (Jaccard) containment. Does sourmash `e1.jaccard(e2)` compute the Jaccard containment instead of resemblance (see below)?

```
# initialize 2 estimators and sketch 2 sequences, then:

a = set(e1.mh.get_mins())
b = set(e2.mh.get_mins())

# isn't this Jaccard containment?
e1.jaccard(e2) == len(a.intersection(b)) / len(a)  # True

# and this Jaccard resemblance/ index?
e1.jaccard(e2) == len(a.intersection(b)) / len(a.union(b))  # False
```

Thank you very much for your help.

**Comment by ctb** [comment]
We only calculate the Jaccard index, i.e. resemblance.  But as you note
it's easy to compute the containment!

**Comment by viehwegerlib** [comment]
But isn't e1.jaccard(e2) actually calculating containment instead of resemblance (see above)? Sorry if I am missing something obvious here.

**Comment by ctb** [comment]
You make a good point - I'll edit my comment. For compatibility with mash, we should maybe do whatever they do.

**Comment by lgautier** [comment]
I believe that MASH is computing the resemblance index as a similarity metric (Jaccard's resemblance index is also called "similarity coefficient"). That index if symmetrical (`J(a, b) == J(b, a)`), which help with the clustering from a matrix of pairwise dissimilarity (a prominent aspect of the work presented in the MASH authors' paper).

The containment index can be useful though. In the context of detection / identification from raw sequencing reads it can be very informative to report the two containment indexes (two since this is not a symmetrical pairwise index) as would tell something along the lines of "your sample contain all of what is in this reference (first containment index) while the reference only represents that much of what is in your sample (second containment index)".

**Comment by viehwegerlib** [comment]
I see, thank you for clarifying this for me. I too think that an explicit resemblance/ containment switch would be very useful, but this is another issue, so I am closing this one.
