### ISSUE TITLE
parallelize SBT

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#126]
Dear all,

Is there some example code on how to parallelize the SBT indexing/ search (via sourmash categorize)? Titus talks about this on his blog, and doing it shouldn't be too difficult, but I thought I'd ask before reinventing the JSON-slicing wheel.

Thank you very much!

**Comment by ctb** [comment]
Hi, I did this just using 'parallel' at the command line; essentially

```
split -l 20000 list_of_sigs.txt
for i in x??
do
	echo sourmash categorize /path/to/sbt $(cat $i) --csv $i.csv
done | parallel -j 8
```

which worked fine for me!  Then I just did `cat $i.csv > all.csv`.

Since the SBT is read only it should be possible to do something with threading
in Python, but I'd be -1 on adding this complexity in the actual sourmash
command.  I'd be happy to explore refactoring the internals a bit to make it
easier to write custom Python scripts that use the sourmash functionality tho.

BTW, the two quickest ways to speed up 'sbt categorize' -- 

* make sure the SBT you're using has JSON signatures. If you're using one of
  our pre-prepared ones, they all have YAML signatures which is much slower.
  Should take < day to fix this for any given collection of signatures,
  happy to explain how.

* we have an unmerged branch, 'sbt_cache', that will cache the signatures.

HTH!

**Comment by viehwegerlib** [comment]
Sry for the late reply. Indeed i ran into the "dog slow" YAML problem (had to laugh at the expression). With JSON everything works fine.

One problem I run into is memory. When trying to index 500k signatures, Python [killed 9](http://stackoverflow.com/questions/34268471/python-killed-9-when-running-a-code-using-dictionaries-created-from-2-csv-files) sourmash sbt_index (8 Gb RAM). 

I understand your reservation about adding the above mentioned complexity. Do you see a way around this problem besides "more RAM", e.g. splitting up the indexing step into multiple ones and then combining the index somehow?

Thx a lot!

**Comment by ctb** [comment]
one additional note - SBT search is reasonably I/O intensive as currently structured, which means that parallelizing it may not help all that much.  But these are things that should be benchmarked...

**Comment by ctb** [comment]
While we've been ignoring this issue, things have changed beyond recognition in the codebase :). Happy to discuss further.

One significant point is that for several years now sourmash supports searching multiple databases, so you can create 5 databases each with 100k signatures and then pass them all in on the command line, and all the commands will work as if you had created one database with 500k signatures.
