### ISSUE TITLE
support krona output?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#178]
https://gist.github.com/taylorreiter/353da32b73242f3686e4967c83de62c8

**Comment by taylorreiter** [comment]
I think supporting krona output is not necessarily the way to go. Perhaps instead outputting NCBI taxonomy number would be a better use of time, so that it's easy for people to feed their results in to a lot of downstream analyses, not just krona.

I like the Krona visualization, but it is glitchy with large-ish datasets (RNAseq, 4M reads).

Originally posted on #174, and added to #195

**Comment by ctb** [comment]
`sourmash lca` and https://github.com/dib-lab/2018-ncbi-lineages now handle various bits of this. `sourmash lca` is the way forward for taxonomy in sourmash, at least for now.
