### ISSUE TITLE
prepared protein search database

### ISSUE THREAD

**Issue by smsaladi** [dib-lab/sourmash#426]
Any chance the sourmash team has a prepared a protein search database that you'd be willing to share?

**Comment by ctb** [comment]
alas, we do not :(

**Comment by SilasK** [comment]
@smsaladi Have you build a protein database? 
How can we prepare one? Download all genomes nucleotides or proteins and follow the instruction to build a new one?

**Comment by smsaladi** [comment]
Yeah, I followed the directions and built one. Probably worth closing this issue

**Comment by SilasK** [comment]
Did you download the proteins or the nucleotides of the genomes?

**Comment by smsaladi** [comment]
Sorry ... if you are asking... yea, download all the genomes you want included and then follow the instructions here:

https://sourmash.readthedocs.io/en/latest/tutorials.html#make-and-search-a-database-quickly

**Comment by smsaladi** [comment]
I made a protein database since the sourmash folks provide ones for refseq and genbank nucleotides: https://sourmash.readthedocs.io/en/latest/databases.html

**Comment by ctb** [comment]
glad to hear the directions worked! I think the right way for us to close this issue is for us to modify our list of prepared databases to indicate that, for the moment, we do not provide such a thing. I'll create a new issue for that so that we don't spam you with comments in the future!

@SilasK you probably want to download the protein, since the 6 frame translation really reduces the sensitivity.

**Comment by ctb** [comment]
I'll close this in favor of #637 - thanks all!

**Comment by SilasK** [comment]
Hallo, can you ask you again, which k-mer you used for the signatures with proteins?
k=30? Should I keep the scaled=1e5 ?
