### ISSUE TITLE
ValueError: num != 0 - cannot downsample a standard MinHash

### ISSUE THREAD

**Issue by superhu0** [dib-lab/sourmash#462]
Hi
when I run sourmash lca gather with a metagenome-assembled sample, like this:
sourmash lca gather final.contigs.10-3.fa.sig genbank-k31.lca.json
I got an error:
loaded 1 LCA databases. ksize=31, scaled=10000
Traceback (most recent call last):
......
query_sig.minhash = query_sig.minhash.downsample_scaled(scaled)
 File "sourmash/_minhash.pyx", line 268, in sourmash._minhash.MinHash.downsample_scaled
ValueError: num != 0 - cannot downsample a standard MinHash

what is the matter and how can I deal with it ? 
HU

**Comment by ctb** [comment]
Hi hu,

create your .sig file with --scaled=1000

best,
--titus

**Comment by superhu0** [comment]
It works, thank you !

**Comment by manu-script** [comment]
Hi @ctb ,
I ran into the same error while creating an LCA index using standard minhash signatures which have scaled=0. Does this mean sourmash LCA currently supports only scaled signatures?

`sourmash sig describe signatures/9605.sig`

signature filename: signatures/9605.sig
signature: 9605
source file:
md5: a31c9bd26a18ec69506ece8ffa27dc85
k=31 molecule=DNA num=1000 scaled=0 seed=42 track_abundance=0
size: 1000
signature license: CC0

`sourmash lca index --traverse-directory taxonomy.csv library.lca signatures/`

examining spreadsheet headers...
54865 distinct identities in spreadsheet out of 54865 rows.
54865 distinct lineages in spreadsheet out of 54865 rows.
... loading signature 30386 (file 1 of 54865); skipped 0 so farTraceback (most recent call last):
  File "/opt/tools/anaconda3/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/opt/tools/anaconda3/lib/python3.7/site-packages/sourmash/__main__.py", line 14, in main
    return mainmethod(args)
  File "/opt/tools/anaconda3/lib/python3.7/site-packages/sourmash/cli/lca/index.py", line 58, in main
    return sourmash.lca.command_index.index(args)
  File "/opt/tools/anaconda3/lib/python3.7/site-packages/sourmash/lca/command_index.py", line 222, in index
    db.insert(sig, ident=ident, lineage=lineage)
  File "/opt/tools/anaconda3/lib/python3.7/site-packages/sourmash/lca/lca_db.py", line 124, in insert
    minhash = minhash.downsample_scaled(self.scaled)
  File "/opt/tools/anaconda3/lib/python3.7/site-packages/sourmash/_minhash.py", line 414, in downsample_scaled
    raise ValueError("num != 0 - cannot downsample a standard MinHash")
ValueError: num != 0 - cannot downsample a standard MinHash

Thanks,
Manu

P.S: num=1000 because I was using a marker gene dataset.

**Comment by ctb** [comment]
yes, I'm afraid LCA databases can only work with scaled signatures! basically it comes down to guarantees about whether or not a relevant hash value will be present if it was seen in the data set.

but what a lousy error message... apologies. I'll make an issue to fix that!

**Comment by J-I-P** [comment]
Hi @ctb,
I have the same error while I run sourmash lca summarize, and my command like,
`sourmash lca summarize --query sample_0.001_single.fastq.sig --db ../genbank-k31.lca.json.gz`
and I also create my .sig file with scaled=1000
```
== This is sourmash version 3.5.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

setting num_hashes to 0 because --scaled is set
computing signatures for files: sample_0.001_single.fastq
Computing signature for ksizes: [31]
Computing only nucleotide (and not protein) signatures.
Computing a total of 1 signature(s).
skipping sample_0.001_single.fastq - already done
```
How can I deal with this?

I have another doubt：
I try to use sourmash to classify zymo data (Zymo mock community Standards 2 (Even)), 
my workflow is below, 
assemble zymo_data.fastq -> sourmash compute zymo_data_assembled.fasta ->sourmash lca summarize or sourmash lca classify zymo_data_assembled.fasta.sig 
Is this workflow is currently?

Thanks for any advice on this!

**Comment by ctb** [comment]
hello @J-I-P! It looks like the .sig file isn't actually created because it already exists -- see the output, `skipping sample_0.001_single.fastq - already done`. You can either remove the .sig file and recreate it, or use `sourmash compute` with `-f` to force overwriting of the old signature.

that workflow should work, yes! let me know if you run into problems and (for that one) please just open a new issue as you need help!

**Comment by ctb** [comment]
(note, you can run `sourmash sig describe sample_0.001_single.fastq.sig` to make sure scaled is non-zero)

**Comment by J-I-P** [comment]
> hello @J-I-P! It looks like the .sig file isn't actually created because it already exists -- see the output, `skipping sample_0.001_single.fastq - already done`. You can either remove the .sig file and recreate it, or use `sourmash compute` with `-f` to force overwriting of the old signature.
> 
> that workflow should work, yes! let me know if you run into problems and (for that one) please just open a new issue as you need help!

thanks, I recreate .sig file and it works!!

OK, I try to build a LCA database ( only bacteria in NCBI) now. I want to use this database to sourmash lca summarize or sourmash lca classify my zymo data.

Thanks for your help.

**Comment by ctb** [comment]
moving LCA database conversation here - https://github.com/dib-lab/sourmash/issues/1264

best,
--titus
