### ISSUE TITLE
gather csv output column "filename" takes from first in list of databases

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#563]
I recently ran sourmash gather with 5 databases simultaneously. The output csv file indicated in the `filename` column that each of my matches were from the first database that I listed, however they were from different databases that I listed.

**Comment by ctb** [comment]
Yep. Bug.

This is a problem encoded in [line 116](https://github.com/dib-lab/sourmash/blob/d2e2e3fd59b4b26416b18a455bd0711254bb2c0d/sourmash/search.py#L116), [line 123](https://github.com/dib-lab/sourmash/blob/d2e2e3fd59b4b26416b18a455bd0711254bb2c0d/sourmash/search.py#L123), and [line 131](https://github.com/dib-lab/sourmash/blob/master/sourmash/search.py#L131) of search.py - we need to append a 3-tuple containing `(similarity, ss, filename)` to `results` instead of the current 2-tuple.

**Comment by ctb** [comment]
Fixed in #589.
