### ISSUE TITLE
Bowtie2 mapping rate >99% but sourmash similarity only 8.5%?

### ISSUE THREAD

**Issue by aditi9783** [dib-lab/sourmash#568]
Hello,

More than 99% paired-end reads (5.5 million total reads) of a clinical isolate mapped to the reference genome (H37Rv).

I wanted to try sourmash to see if there are other bacterial species present in the WGS data.

I created a database using three genomic fasta sequences, one belonging to the reference and two from other clinical samples (created signatures for the fasta sequences and then generated database mtbdb.sbt.json using 'index' command).

However, when I tried `sourmash search`, I got only 8.5% similarity to the reference genome.

Did I make a mistake in running sourmash? If not, how do I interpret this result?

When I ran `sourmash gather` using the 

All the commands I ran are below:
1. Generate signature for the paired end reads:
`$ sourmash compute --scaled 10000 ../data/ERR1063836_*.gz --merge ERR1063836.sig -o ERR1063836.sig -k 31`

2. Create database:
`$ sourmash compute --scaled 10000 Mtb_beijing.fasta -o Mtb_beijing.sig -k 31`
`$ sourmash compute --scaled 10000 Mtb_HN024.fasta -o Mtb_HN024.sig -k 31`
`$ sourmash compute --scaled 10000 Mtb_H37Rv.fasta -o Mtb_H37Rv.sig -k 31`
`$ sourmash index -k 31 mtbdb Mtb_*.sig
loading 3 files into SBT
loaded 3 sigs; saving SBT under "mtbdb"

Finished saving nodes, now saving SBT json file.`

3. Running sourmash search:
`$ sourmash search signatures/ERR1063836.sig databases/Mtb_lineages/mtbdb.sbt.json
select query k=31 automatically.
loaded query: ERR1063836.sig... (k=31, DNA)
loaded 1 databases.

3 matches:
similarity   match
----------   -----
  8.5%       Mtb_H37Rv.fasta
  8.4%       Mtb_HN024.fasta
  8.4%       Mtb_beijing.fasta`

Thanks in advance!

**Comment by ctb** [comment]
mapping is much looser than k-mer matching - e.g. Jaccard similarity (k-mers)
is always lower than average nucleotide identity.

separately: if you are doing this with reads instead of assemblies, then
the reads contain a lot of errors that will introduce novel k-mers that
will not match and will decrease Jaccard similarity. If you are working
with reads, you might try adding --containment to the sourmash search
commands below - that will only look at the degree to which the query
is contained in the matches, not the full Jaccard similarity.

hth!

--titus

**Comment by aditi9783** [comment]
Thank you, Titus. That is very helpful.
