### ISSUE TITLE
filter hashes from signatures with abundance < 1

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#601]
This could be useful for signatures that represent reads that have not been k-mer trimmed

**Comment by ctb** [comment]
well, technically, hashes with abundance < 1 are not going to be present <grin>. Probably you mean k-mers with abundance below 2...

This is an interesting idea. A few thoughts --

* from the point of view of separation of concerns, it seems like k-mer trimming is best left to another package, like, oh, say, khmer. since khmer and sourmash both support streaming I am wondering if there is a strong benefit over the process suggested [here](https://sourmash.readthedocs.io/en/latest/using-sourmash-a-guide.html#how-should-i-prepare-my-data) which uses khmer?
* note, mash does already do this using bloom filters etc etc
* k-mer abundance tracking is annoying and memory intensive, so I was asking myself, why don't we just collect abundances for all recorded k-mers in the signature, and then support removal of low abundance  k-mers after the signature has been created? and then I realized this works fine for scaled signatures, but not for regular MinHash! hah!

anyway, those are my thoughts.

certainly I think a postprocessing command that eliminates low-abundances hashes from the sourmash signature is easy to do & worth doing. whether it resolves this issue is a different question :)

**Comment by ctb** [comment]
a specific use case for this that @taylorreiter had in mind all along and I just now understood: looking at Nanopore sequences, where trim-low-abund is inappropriate (because it trims the sequences, which works fine for Illumina but is a bad idea for Nanopore!)

This would actually be addressed by https://github.com/dib-lab/khmer/issues/1615 quite nicely...
