### ISSUE TITLE
sourmash gather `--output-unassigned` outputs nothing when there are no gather matches

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#612]
Using the command:
```
sourmash gather -o tmp-CSM7KOOR.gather --save-matches tmp-CSM7KOOR.matches --output-unassigned tmp-CSM7KOOR.un --scaled 2000 -k 51 outputs/sigs/CSM7KOOR.scaled2k.sig inputs/databases/genbank-d2-k51.sbt.json
```
the signature `tmp-CSM7KOOR.un` is empty. This only occurs when there are no gather matches. 

```
$ sourmash info
sourmash version 2.0.0a9
```

**Comment by ctb** [comment]
So I started to do this in #613 and then ran across the following code:

https://github.com/dib-lab/sourmash/blob/fix/gather_unassigned/sourmash/commands.py#L1106

which makes it seem like this was intended behavior (although there was a bug even so, since the 'nothing found - entire query signature unassigned' message wasn't printed out).

I'm not sure what the right behavior should be. Output nothing, or output everything?

**Comment by ctb** [comment]
makes sense! thx.
