### ISSUE TITLE
question on sourmash lca index behaviour

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#650]
My use case is that I want to index a set of genomes in a folder using `sourmash lca index`, but I want to leave out some of them as a holdout/ test set. When I remove the genomes from the `taxonomy.csv` file, my intuition is that they are not included in the index. However, when I `grep` for the holdout UIDs, I find them in the `lca.index.json`. So come time for `sourmash lca classification`, will the holdout genomes be "used" or not?

Thank you very much!

**Comment by ctb** [comment]
Hi @phiweger, sorry,  I missed this!

Yes, if the genomes have no taxonomic assignments, they are not used for classification purposes.

The genomes are included in the databases, however, because that way commands like `sourmash gather` work as expected on the full set of genomes. In #798 we added the `--require-taxonomy` which does what you were expecting here, and declines to include genomes that are not in taxonomy.csv.
