### ISSUE TITLE
The amount of K-mer generated from a sequence is sometimes wrong

### ISSUE THREAD

**Issue by dgg32** [dib-lab/sourmash#660]
Hello Developers. I have the following code to demonstrate:

```
import sourmash

seq3 = "ATGCAT"

k_size = 3

E3 = sourmash.MinHash(n=100, ksize=k_size)

E3.add_sequence(seq3)

E3.get_mins()  ## I also tried E3.get_hashes(), the same output
```
Which should contain 4 unique hashes (ATG, TGC, GCA, CAT)

But the output is:
`[3115010115530738562, 5059920851104263793]`

How come there are only 2? Something is wrong here?

More specifically, two different sequences have the same hash:
```
import sourmash
seq1 = "TGC"
seq2 = "GCA"

k_size = 3

E1 = sourmash.MinHash(n=100, ksize=k_size)
E2 = sourmash.MinHash(n=100, ksize=k_size)

E1.add_sequence(seq1)
E2.add_sequence(seq2)

E1.get_hashes() == E2.get_hashes()
```

Which returned "True"

So apparently the reverse complements got the same md5. Because sourmash computes both the forward and reverse strands and then takes the smaller one to represent the k-mer? It make sense in some cases. But in this case, it will get results different from the expected behavior.

Thank you!

**Comment by ctb** [comment]
This is because of reverse complements - CAT is the reverse complement of ATG so sourmash only takes one (the lexically lower of the two).

best,
—titus
--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Mar 29, 2019, at 6:32 AM, dgg32 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Developers. I have the following code to demonstrate:

import sourmash

seq3 = "ATGCAT"

k_size = 3

E3 = sourmash.MinHash(n=100, ksize=k_size)

E3.add_sequence(seq3)

E3.get_mins()


Which should contain 4 unique hashes (ATG, TGC, GCA, CAT)

But the output is:
[3115010115530738562, 5059920851104263793]

How come there are only 2? Something is wrong here?

Thank you!
