### ISSUE TITLE
Bioconda version differs from pip version

### ISSUE THREAD

**Issue by Garrus990** [dib-lab/sourmash#686]
Hi,

when I was trying to install `sourmash` from different sources I discovered, that whereas `pip`-installation for python 3.6 installs what I expect, `conda`-installation does not. The former case installs `sourmash-2.0.0` and the latter (`bioconda` channel) `sourmash-1.0`. 

Additionally, the command you suggest in the Readme.MD file to use in order to install `sourmash` for `conda` does not work as without channel specification `sourmash` package cannot be found.

Cheers,
Szymon

**Comment by matrs** [comment]
In general, most of the packages in bioinformatics are in the `bioconda` channel, maybe that's why isn't mentioned in the readme. I would suggest you to go to [bioconda](https://bioconda.github.io/user/install.html#install-conda) and see their installation and setup instructions if you have doubts. Also, when you use conda, what get installed depends on your environment. If you have doubts about that, you can check `conda`'s documentation. If you have python 3.6 in your conda env, you can try `conda install sourmash=2.0.1` or any other version compatible with your python version. Also, you can specify the `Build` version, like this:
`conda install sourmash=2.0.1=py36hf484d3e_0 `

It's useful to specify the version you want because `conda` may get slow if you have many dozens of packages installed in your environment, so many times it's the recommended way to use it, although, it's never mandatory.

**Comment by ctb** [comment]
hi @Garrus990, thank you for reporting this! I'm not sure what went wrong, but the latest bioconda package is 2.0.1 - see https://bioconda.github.io/recipes/sourmash/README.html?highlight=sourmash#recipe-Recipe%20&#x27;sourmash&#x27;.

In #717 I've updated the README to include a channel spec for the basic conda install.
