### ISSUE TITLE
Question: Rust code advantages

### ISSUE THREAD

**Issue by pranathivemuri** [dib-lab/sourmash#703]
I have observed that your rust codebase touches the signature function. Did you have a  time performance improvement after this change in the signatures module and what was it? Are you planning to change the minhash calculation or any other part of the code for similar time performance improvement?

**Comment by ctb** [comment]
On Wed, Jul 31, 2019 at 08:44:03AM -0700, Pranathi Vemuri wrote:
> 1) Hi, I am Pranathi, I am currently working with Olga on the CZ biohub team trying to use sourmash for converting bam to fasta and then convert fasta to signatures. When the bam file is really large like 20 GB, sourmash CPU usage increases to 100% and it hangs. Have you observed a behaviour like this before. Do you have any proposed or solutions in progress for similar problems. I am using multiprocessing.pool and computing signatures on smalller bam files after chunking and saving them outside of memory. Its a work in progress right now on this branch - https://github.com/czbiohub/sourmash/compare/pranathi-10x...pranathivemuri:pranathi-10x?expand=1 as it seems like joblib Parallel and delay is bad combo for arguments that are huge - https://github.com/scikit-learn/scikit-learn/issues/3835

Hi pranathi, I haven't used that code, so I don't know! But there was a memory
leak fixed recently, please see #685 and #687! This might be the problem
in #559...

> 2) I have observed that your rust codebase touches the signature function. Did you have a  time performance after this change in the signatures module? Are you planning to change the minhash calculation or any other part of the code for similar time performance improvement?

the future of the sourmash code is in rust, where we will apply targeted
optimizations as needed. No more specific info than that available at the
moment (please see #692 tho).

as a side note, in the future please file multiple issues if there are two
unrelated topics - that way we can track them separately!

best,
--titus

**Comment by ctb** [comment]
ahh, I see you broke out the first question into #704, thanks :)

**Comment by luizirber** [comment]
> the future of the sourmash code is in rust, where we will apply targeted
optimizations as needed. No more specific info than that available at the
moment (please see #692 tho).

Oh, #692 is a terrible PR to point because it doesn't explain what it does =P

> 2) I have observed that your rust codebase touches the signature function. Did you have a  time performance after this change in the signatures module? Are you planning to change the minhash calculation or any other part of the code for similar time performance improvement?

The `compute` command is not available in Rust yet, but #424 already uses Rust for the lower level parts. The signature parts (to be integrated in #532) focused more on loading/saving signatures, and for that it is a lot faster (I have a 200 MB signature around that took minutes to load currently, but takes 10 seconds to load in Rust).

I would like to explore a bit the 10x compute case in Rust because 10x genomics does quite a bit of Rust development, and they probably have a crate for loading their data (and it's also easier to do parallel computing in Rust).

I posted a comment in #556 that has some discussion about indices and more plans for Rust/Python integration:
https://github.com/dib-lab/sourmash/pull/556#issuecomment-524154632

**Comment by ctb** [comment]
There have now been lots of discussion about rust, performance, etc. Here are some twitter threads:

https://twitter.com/ctitusbrown/status/1207309093204938752
https://twitter.com/luizirber/status/1207374857962475520

 I am going to close this, but I welcome @luizirber dropping in more links :)
