### ISSUE TITLE
Large bam files and sourmash compute

### ISSUE THREAD

**Issue by pranathivemuri** [dib-lab/sourmash#704]
Hi, I am currently working with @olgabot  on the CZ biohub team trying to use sourmash for converting bam to fasta and then convert fasta to signatures. When the bam file is really large like 20 GB, sourmash CPU usage increases to 100% and it hangs. Have you observed a behaviour like this before. Do you have any proposed or solutions in progress for similar problems. I am using multiprocessing.pool and computing signatures on smalller bam files after chunking and saving them outside of memory. Its a work in progress right now on this branch - https://github.com/czbiohub/sourmash/compare/pranathi-10x...pranathivemuri:pranathi-10x?expand=1 as it seems like joblib Parallel and delay is bad combo for arguments that are huge - https://github.com/scikit-learn/scikit-learn/issues/3835

**Comment by luizirber** [comment]
Hmm, I remember seeing slowdowns with some euk genomes, but didn't check in detail what was happening.

I would like to explore a bit the 10x compute case in Rust because 10x genomics does quite a bit of Rust development, and they probably have a crate for loading their data (and it's also easier to do parallel computing in Rust).

**Comment by ctb** [comment]
10x compute has been removed for 4.x per https://github.com/dib-lab/sourmash/pull/1229
