### ISSUE TITLE
Basic usability problems with genbank SBT

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#716]
This is going to be a bit of a meta issue, but it is also a separate UX issue.

With the genbank-d2 update, it's become quite hard to actually use the genbank SBT. A few issues -

* it's too big to unpack on Jetstream - it's in the ~30 GB range
* it's too slow to search on my laptop, even with `sbt gather`.

I know there are various things being worked on that could help with these issues, and I want to collect them here.

**Comment by ctb** [comment]
One note is that 'sourmash gather -n <N>` could truncate the search at that point.

**Comment by ctb** [comment]
Supporting direct compressed sbt.json archives (.zip or .tar.gz?) would be a big step.  See #648.

**Comment by luizirber** [comment]
Biggest issue with #648 is that... it's kind of slow (but I think there are some ZIP tricks than can be played to make it faster).

The size of the SBT is due to changes on internal node sizes, but we can revert that. Clustering the SBT will also help (https://github.com/dib-lab/sourmash/pull/710#issuecomment-524141182), because we can compress the internal nodes better.

Oh, and I don't think we are compressing the internal nodes, which is also something that is relevant to #648 (stored nodes compressed inside the ZIP, and use the ZIP format just for single file distribution).

**Comment by ctb** [comment]
ref #646

**Comment by ctb** [comment]
With #799 and #648 now merged, many of these issues should be resolved - will regenerate databases and see what happens :). #925 is the next likely candidate for performance improvements on SBTs and large databases, specifically.

**Comment by ctb** [comment]
the remaining usability problems are mostly around NCBI taxonomy issues... see https://github.com/dib-lab/sourmash_databases/issues/8
