### ISSUE TITLE
Bug when install sourmash

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [dib-lab/sourmash#874]
Weirdly fast bug filing, but I just got this error when installing sourmash in a docker image:

14.49     copying sourmash/cli/storage/__init__.py -> build/lib/sourmash/cli/storage
14.49     copying sourmash/cli/storage/convert.py -> build/lib/sourmash/cli/storage
14.49     error: [Errno 2] No such file or directory: 'cargo': 'cargo'

14.60 Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cpq1iosk/sourmash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dxb7w5bp/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-cpq1iosk/sourmash/

Guessing this might be related to the pull request that was just merged. Should be python 3.7.2 on Ubuntu 18.04 LTS.

**Comment by luizirber** [comment]
Since sourmash 3.0.0 we have a Rust codebase, so if you're building from source you need a Rust compiler (`>=1.34.0`) installed. The command on the [dev docs] should suffice:
 `curl https://sh.rustup.rs -sSf | sh`

If you're using a conda environment, you can also install from conda-forge:
`conda install -c conda-forge rust`

[dev docs]: https://sourmash.readthedocs.io/en/latest/developer.html#development-environment

**Comment by luizirber** [comment]
I'm also in the process of releasing `3.2.0`, so it's missing the wheels and bioconda release for now. Should be ready in an hour =]

**Comment by jdwinkler-lanzatech** [comment]
This is via pip actually, so probably coincidental timing on my part!

**Comment by luizirber** [comment]
OK, wheels are up, so `pip install sourmash` should work now!

**Comment by jdwinkler-lanzatech** [comment]
Awesome, thanks for the quick response.
