### ISSUE TITLE
Revisit names and hierarchy

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#88]
A few things for @lgautier and @luizirber to weigh in on --

* the `sourmash_lib.signature` module is badly named; I keep on colliding names with `sig`, etc. I was thinking of renaming it `sigutils` or something.

* the `Estimators` class is badly named. It's a legacy class anyway, held over from when MinHash didn't exist. It's still a convenient wrapper around the CPython `MinHash` class, at least for now, since pure Python is much easier to write, change, and test than new C code. One approach might be to deprecate the direct use of `MinHash` and wrap it more tightly in `Estimators`, and then rename `Estimators` to `MinHash`. Or if that's too confusing, `MinHashWrapper`. Thoughts?

* regardless of what we do with the names, `Estimators` should be moved out of `__init__.py`.

Not hugely urgent but if you have super strong opinions, now is the time :)

**Comment by lgautier** [comment]
Just opinions: 

- I prefer `signature` to `sigutils` (the later bringing little IMHO - to take a parallel, I like better the stdlib package `os` to be called that way rather than `osutils`). Not saying that `signature` should not be named anything else though...

- I agree that `Estimators` is not the best name for what it represents. The C-level class could be `_MinHash` (or better `_MinHashSketch`, since this is a collection of hash values)  while the Python-level wrapper be simply `MinHash` (or `MinHashSketch`). That's strategy I like because it lets one implement ideas in Python and only move what is both meant to stay and performance-critical down to C as needed.

**Comment by ctb** [comment]
The 'estimators' class was completely removed and now 'Signature' has a 'minhash' member, as of #155. We'll leave 'signature' as is, as suggested by @lgautier.
