### ISSUE TITLE
readthedocs fails to auto-import API docs

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#894]
See [log file](https://readthedocs.org/projects/sourmash/builds/10404611/) - the problem seems to be

```
WARNING: autodoc: failed to import module 'sourmash'; the following exception was raised:
No module named 'sourmash._lowlevel'
```

this is presumably because the rust stuff is not built?

**Comment by ctb** [comment]
ok, but it _is_ built? odd. still looking.

**Comment by ctb** [comment]
even odder, it works on my test branch... https://sourmash.readthedocs.io/en/refactor-minhash/api.html

**Comment by luizirber** [comment]
I think this is related to our [non-`src/`][0] repo layout. I had similar issues in #696 (with `coverage` counting not lines in the installed package, but in the `sourmash/` dir), and in this case it's because the `sourmash` package is being installed... but it's the `sourmash/` dir that is being used during runtime.

Short term solution: install the package with `-e .` (and then `_lowlevel.py` will be available).

But I think we should move to `src/` layout =]

[0]: https://bskinn.github.io/My-How-Why-Pyproject-Src/

**Comment by luizirber** [comment]
Update: I don't think readthedocs supports `-e .` or `develop` installs...

**Comment by ctb** [comment]
On Sat, Feb 08, 2020 at 07:15:38PM -0800, Luiz Irber wrote:
> But I think we should move to `src/` layout =]

I'm good with this for 4.0.

**Comment by ctb** [comment]
this seems to be working now. see: https://sourmash.readthedocs.io/en/latest/api.html
