### ISSUE TITLE
sourmash documentation

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash#901]
After some struggle and googling through the repo, I found [this "internal" API documentation](https://github.com/dib-lab/sourmash/blob/7af043aa15a83158462f2deef5a12019ced9198c/doc/api-example.md) much better than the ["official" one](https://sourmash.readthedocs.io/en/latest/api.html). It might be helpful to link it?

**Comment by phiweger** [comment]
Can't believe I overlooked that, sorry.

**Comment by ctb** [comment]
hi @phiweger one problem is that the "official" API documentation [isn't getting built properly](https://github.com/dib-lab/sourmash/issues/894). So that's something we're working on fixing. The official docs did get a bit of a potential upgrade in #889, but of course that's not reflected in the current docs because of the bug above.

In our actually fairly reasonable defense, the docs you eventually found _are_ linked directly at the top of the not-so-useful ones <grin>.

**Comment by phiweger** [comment]
that defence is very justified, I did realise there was a link like 0.5 seconds after posting the issue :)
