### ISSUE TITLE
sourmash lca summarize should work differently on signatures calculated with --singleton

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/sourmash#914]
Right now, if `sourmash lca summarize` is run with a signature that was calculated using the `--singleton` flag, `lca summarize` does not output a result per sketch within the signature, and only outputs a single result that summarizes the entire signature. I think it would be helpful to have this either not be the default behavior, or add a flag for `--singleton` to output an `lca summarize` summary for each of the sketches in the signature (that match the k-size).

**Comment by ctb** [comment]
this is a great idea, and is straightforward to implement. however the current summarize output doesn't contain the filename(s) or name(s) of the input signature(s). so the question is, what do we do?

one option is to create a new command. blech.

another is to have the `--singleton` flag provide a different output format. blech.

a third is to modify the output to include that information, as well as provide a `--singleton` flag. that would require a new major release.

**Comment by taylorreiter** [comment]
What about outputting a flag for `--singleton` that outputs the same lca format, but one per a signature? we could prepend or append the output file name with the singleton sketch names in the signature or something?

**Comment by luizirber** [comment]
> a third is to modify the output to include that information, as well as provide a `--singleton` flag. that would require a new major release.

how about a `--output-filename` (or something like that) that adds the column to the output, and deprecate it in `4.x` (and make it the default)?

**Comment by ctb** [comment]
OK, dug into the code a little bit (see #922).

I think there are three possible behaviors (let's call them `--singleton`, `--merge-in-file`, and `--merge-all`.

1. `--singleton` does what is wanted here - it summarizes each signature individually, and outputs filename and signature name with summary.
2. `--merge-all` is the current default - it combines all signatures, and outputs a summary classification with no filename/signature name.
3. `--merge-in-file` might be a different desired behavior, wherein all signatures in a given file are merged, and a summary classification per file is made available.

After implementing (1) and (2) in #922, and gazing upon the code wreckage that resulted, I have formed a firm opinion that `--singleton` is the right default behavior. The reasons are as follows --

- `sourmash compute` by default does `--merge-in-file`, and provides options for `--singleton` and `--merge-all`.
- if you did an expensive signature computation with `--singleton` and don't want to recompute the signatures/don't have the original files any more `sourmash signature merge` will let you merge things anyway.
- I'm struggling to come up with any _other_ reasonable use for the current default behavior, `--merge-all` that couldn't be resolved by using `sourmash sig merge`.
- it Just Makes Sense in terms of the output functionality to summarize each *signature* - otherwise you have variable output formats depending on the parameters (`--singleton`? ok, output filename, sig name, AND md5; `--merge-in-file`? ok, output just filename; `--merge-all`? ok, don't output filename.)

SO, I propose that we just add `--singleton` now, and special case the output appropriately; then remove the merge behavior for 4.x and just default to `--singleton` after that.

I'll wait a few days for comments and then if there aren't any, I'll update & simplify #922 to match and put it up for review.

**Comment by ctb** [comment]
making it so!
