### ISSUE TITLE
Add option to use majority vote instead of LCA for taxonomic classification

### ISSUE THREAD

**Issue by apcamargo** [dib-lab/sourmash#984]
Hey all!

I've been playing with contig-level taxonomic classification for a while and I noticed that most of the times taking the LCA is too "pessimistic" and often results in a high-rank classification (domain, phylum, class). After some testing I've noticed that taking the majority vote usually gave me more specific taxa without over-classification.

It is important to note that I'm using the majority vote approach to go from gene-level classification to contig-level classification. As k-mer data is probably noisier, it may not work as well as it did for me.

As at the time I coulnd't find a Python implementation of the majority vote algorithm, I ended up creating a [package just for that](https://github.com/apcamargo/taxopy/blob/master/taxopy/utilities.py#L61) (@luizirber I promisse I'll try to implement it in [taxonomy](https://github.com/onecodex/taxonomy) as soon as I got the time!).

**Comment by ctb** [comment]
Hi Antonio,

totally agree - see sourmash lca summarize for something that provides
the necessary info.

In charcoal (dib-lab/charcoal) we are working on using minority classifications
to decontaminate genome bins, too.

thanks!

**Comment by apcamargo** [comment]
Thanks @ctb! I'll take a look!

**Comment by luizirber** [comment]
Another issue with LCA: if synthetic constructs are present, LCA will go back to the root.

Similar issue in mmseqs2: https://github.com/soedinglab/MMseqs2/issues/312

**Comment by ctb** [comment]
@erikyoung85 I _think_ the work for this involves providing an option to `sourmash lca classify` that eliminates the for loop, here:

https://github.com/dib-lab/sourmash/blob/master/sourmash/lca/command_classify.py#L52

and only uses the first result from `counts.most_common()`.

For a test case, I'm going to throw you into the deep end a bit :). Try this -- write a new test in `test_lca.py` that:

1. builds an LCA database using lca index per `test_lca.py:test_index_and_classify_internal_unassigned_multi()`
2. builds a merged ksize=31 signature that contains the hashes from both `TARA_ASE_MAG_00031.sig` and `TARA_PSW_MAG_00136.sig`
3 classifies that signature using the new command line option, and instead of yielding a 'disagree' (which is what the current classify would do), yields a `Eukaryota;Chlorophyta;Prasinophyceae;unassigned;unassigned;Ostreococcus` classification

----

For testing the output of (1) and (2), you can try:

```
sourmash lca classify --db XXX.lca.json --query combined.sig
```
and you should get
```
86.0%  1231   Eukaryota;Chlorophyta;Prasinophyceae;unassigned;unassigned;Ostreococcus
86.0%  1231   Eukaryota;Chlorophyta;Prasinophyceae;unassigned;unassigned
86.0%  1231   Eukaryota;Chlorophyta;Prasinophyceae;unassigned
86.0%  1231   Eukaryota;Chlorophyta;Prasinophyceae
86.0%  1231   Eukaryota;Chlorophyta
86.0%  1231   Eukaryota
14.0%   200   Bacteria;Proteobacteria;unassigned;unassigned;Alteromonadaceae
14.0%   200   Bacteria;Proteobacteria;unassigned;unassigned
14.0%   200   Bacteria;Proteobacteria;unassigned
14.0%   200   Bacteria;Proteobacteria
14.0%   200   Bacteria
```

happy to take more questions here or in a PR :)
