### ISSUE TITLE
What does `--threshold-bp` do in `sourmash gather` ?

### ISSUE THREAD

**Issue by metajinomics** [dib-lab/sourmash#995]
Hi, 

I noticed that I have fewer rows in the result of `sourmash gather` after version v3.2.3. It returns 2/3 of the result compared to the previous version in some of my samples. Also, I noticed that a bug `--threshold-bp=0` was fixed at the version from the release note. Those removes have happened at the bottom of the result, however, it was not necessary for a low value of `f_unique_weighted`. I was worried that some of removed row contains over 0.002(which means 0.2 % in my understanding) in `f_unique_weighted`. 

1. Can I ask what does --threshold-bp do? The name indicates me something similar to "aligned base pair". Is it means result to return if more than 2 k-mer hit if I set --threshold-bp = 100 when I set -k=51?
2. Can I ask what is the default value?

Many thanks,
Jin

**Comment by ctb** [comment]
hi jin will answer soon - @taylorreiter had same question in #976!

**Comment by ctb** [comment]
as an initial answer about what `--threshold-bp` is _supposed_ to do,

* suppose you set `--scaled` to 10,000 in your signatures and database. that means that for every 10,000 distinct k-mers, on average sourmash compute will have selected one hash. So in a contiguous genome, each hash would "represent" a block of about 10kb. (This matches reality, from the statistics we've seen.)
* now, if you set `--threshold-bp` to 50kb (which is the default), sourmash gather will report matches that share 5 or more hashes, representing approximately 50kb of estimated overlap.
* that's the best case, where the query and database contain exact DNA overlap. in practice, this is different in hard-to-measure ways when there is sequence divergence. the stats in the MetaPalette paper can give you some indication of how this works if you're interested in digging.

The previous behavior was _effectively_ 0 in many situations but due to some code complexity there was hard-to-explain behavior.

The k-mer size itself does not particularly matter except when you have divergent sequence, in which case lower k-mer sizes are more sensitive to more divergent overlaps (again, see MetaPalette).

Will answer around comparison with previous behavior separately.

**Comment by metajinomics** [comment]
Thank you very much for your answer. Now, I understand what `--threshold-bp` do. Looking forward to your separate answer about comparison with the previous behavior. 👍

**Comment by ctb** [comment]
Hi @metajinomics I think I figured it all out :). Please take a look at https://github.com/dib-lab/sourmash/issues/976#issuecomment-634214844. Happy to discuss further!

**Comment by ctb** [comment]
Closing for now - documentation and code updated in #1001. Let me know if you have any more questions!

**Comment by metajinomics** [comment]
Thank you very much for your answer :)
